In [1]:
import torch

In [18]:
tensor1 = torch.randn(10, 2)
print(tensor1)
tensor2 = tensor1.view(5, 2, 2)
print(tensor2)

tensor([[ 0.5763, -0.1681],
        [ 0.3528, -1.2747],
        [ 0.1138,  0.8957],
        [-0.6074,  0.2730],
        [ 0.6778, -0.1365],
        [-0.4219,  0.2173],
        [-0.6217,  0.3097],
        [-0.5737, -0.0260],
        [-0.6076, -2.1961],
        [ 0.6156,  0.9959]])
tensor([[[ 0.5763, -0.1681],
         [ 0.3528, -1.2747]],

        [[ 0.1138,  0.8957],
         [-0.6074,  0.2730]],

        [[ 0.6778, -0.1365],
         [-0.4219,  0.2173]],

        [[-0.6217,  0.3097],
         [-0.5737, -0.0260]],

        [[-0.6076, -2.1961],
         [ 0.6156,  0.9959]]])


In [19]:
for i in tensor2:
    print(i)

tensor([[ 0.5763, -0.1681],
        [ 0.3528, -1.2747]])
tensor([[ 0.1138,  0.8957],
        [-0.6074,  0.2730]])
tensor([[ 0.6778, -0.1365],
        [-0.4219,  0.2173]])
tensor([[-0.6217,  0.3097],
        [-0.5737, -0.0260]])
tensor([[-0.6076, -2.1961],
        [ 0.6156,  0.9959]])
