In [2]:
import dgl
import torch

In [3]:
graph = dgl.rand_graph(10, 10)

In [36]:
feats = graph.in_degrees()
print(feats)

tensor([1, 1, 0, 2, 0, 1, 0, 1, 0, 4])


In [37]:
feats = feats.view(10,1)

In [38]:
feats = torch.cat((feats, torch.zeros(10, 1)), dim=1)
print(feats)

tensor([[1., 0.],
        [1., 0.],
        [0., 0.],
        [2., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [4., 0.]])


In [29]:
feats = feats.to(torch.int64)

In [19]:
feats2 = torch.zeros(10)
print(feats2)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [20]:
graph.ndata['x'] = feats
graph.ndata['y'] = feats2

In [21]:
graph.ndata

{'x': tensor([1, 1, 0, 2, 0, 1, 0, 1, 0, 4]), 'y': tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])}

In [13]:
for nodes in graph.nodes():
    print(nodes.ndata('x'))

AttributeError: 'Tensor' object has no attribute 'ndata'

In [14]:
graph.ndata['x']

tensor([1, 1, 0, 2, 0, 1, 0, 1, 0, 4])